work_dir: ./work_dir/kaggle/xsub/unik_joint
model_saved_name: ./runs/kaggle/joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/kaggle/xsub/train_data_joint.npy
  label_path: ./data/kaggle/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/kaggle/xsub/val_data_joint.npy
  label_path: ./data/kaggle/xsub/val_label.pkl

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 49
  num_joints: 20
  num_person: 2
  in_channels: 3
  num_heads: 4

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 50]

# training
device: [5]
batch_size: 32
test_batch_size: 64
num_epoch: 60
nesterov: True

