work_dir: ./work_dir/kaggle/unik_joint
model_saved_name: ./runs/kaggle/joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/kaggle/train_data_joint.npy
  label_path: ./data/kaggle/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/kaggle/val_data_joint.npy
  label_path: ./data/kaggle/val_label.pkl

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 49
  num_joints: 20
  num_person: 1
  in_channels: 3
  num_heads: 3

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 50]
#optimizer: AdaBound

# training
seed: 42
device: [5]
batch_size: 64
test_batch_size: 128
num_epoch: 100
nesterov: True

