# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kaggle/val_data_joint.npy
  label_path: ./data/kaggle/val_label.pkl
  debug: False

# model
model: model.backbone_unik.UNIK
model_args:
  num_class: 49
  num_joints: 20
  num_person: 1
  in_channels: 3
  num_heads: 3
  
# test
phase: test
device: [5]
test_batch_size: 64
weights: ./runs/kaggle/joint-39-5800.pt
work_dir: ./work_dir/unik_test_joint
model_saved_name: ./runs/val_res
save_score: True
